### ISSUE TITLE
How to change python path of nvim-dap-python dynamically

### ISSUE THREAD

**Issue by vpeopleonatank** [theHamsta/dotfiles#1]
In your `init.lua`, I saw this line `require("dap-python").setup("/usr/bin/python3")`. It fixed python path. Do you have some ways to change python path dynamically? If you know, can you suggest me, because I have some anaconda python env and use them in  each project.

**Comment by theHamsta** [comment]
You could just use this function that I stole from the nvim-dap wiki or just `vim.fn.exepath('python')` if you started Neovim vim with an activated virtual env.
```lua
pythonPath = function()
      -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
      -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
      -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
      local cwd = vim.fn.getcwd()
      if vim.fn.executable(cwd .. '/venv/bin/python') then
        return cwd .. '/venv/bin/python'
      elseif vim.fn.executable(cwd .. '/.venv/bin/python') then
        return cwd .. '/.venv/bin/python'
      else
        return '/usr/bin/python'
      end
    end;
```

**Comment by vpeopleonatank** [comment]
> You could just use this function that I stole from the nvim-dap wiki or just `vim.fn.exepath('python')` if you started Neovim vim with an activated virtual env.
> 
> ```lua
> pythonPath = function()
>       -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
>       -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
>       -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
>       local cwd = vim.fn.getcwd()
>       if vim.fn.executable(cwd .. '/venv/bin/python') then
>         return cwd .. '/venv/bin/python'
>       elseif vim.fn.executable(cwd .. '/.venv/bin/python') then
>         return cwd .. '/.venv/bin/python'
>       else
>         return '/usr/bin/python'
>       end
>     end;
> ```

Thanks for your help.

**Comment by theHamsta** [comment]
But nvim-dap-python says
```
The argument to setup is the path to the python installation which contains the debugpy module.
```
This should not be necessary to make it dynamic since you probably can have only one install location for the debugpy and nvim-dap-python will find out the interpreter for the virtualenv for you: https://github.com/mfussenegger/nvim-dap-python/blob/32df1554f737eb93f60a6ad11406ad246d6e0399/lua/dap-python.lua#L8 (I assume that debugpy can do this cross-debugging from different interpreters)

**Comment by vpeopleonatank** [comment]
As you point out, I can change `$VIRTUAL_ENV` to python path and `nvim-dap-python` automatically use it.

**Comment by theHamsta** [comment]
> s you point out, I can change $VIRTUAL_ENV to python path 

this happens automatically on `source ./bin/activate
